name: deploy-auction

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  DEPLOYMENT_NAME: auction-svc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save cubeauction
      
      - name: Restart kubernetes deployment
        run: kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}
